OpenGeoscience/uvdat

uvdat/core/serializers.py
uvdat/core/views.py
web/src/api/rest.ts
web/src/components/OptionsDrawerContents.vue
web/src/types.ts
web/src/utils.js

This PR adds a toggle switch to the Options panel for any dataset where `network=True`. 
When enabled, the normal layer is hidden and a new layer with the network representation is created (or shown if it already exists). For now, this visualization is static and does not have special interaction options (such as marking nodes as inactive). It does have the tooltip interaction to view the details of a node.

Network vis

---

sample_data/populate_server.py
uvdat/core/tasks/conversion.py
uvdat/core/tasks/networks.py
uvdat/core/views.py

This PR adds a new celery task called `network_gcc`, which accepts two parameters `edge_list` and `exclude_nodes`. For now, this task is empty except for a print statement. This will be a placeholder for where we will invoke the code from NU.
This PR also adds an endpoint for spawning the new task, and it does a bit of mild refactoring. To avoid overloading the `tasks.py` file, this PR splits the celery tasks into two files: `tasks/conversion.py` and `tasks/networks.py`.

Blank analysis task

---

sample_data/datasets.json
setup.py
uvdat/core/tasks/networks.py
uvdat/core/views.py
web/src/api/rest.ts
web/src/components/DrawerContents.vue
web/src/components/OpenLayersMap.vue
web/src/components/OptionsDrawerContents.vue
web/src/store.ts
web/src/utils.js

This PR incorporates @johnkit's `compute_gcc` function. These changes allow the user to select nodes and mark them as deactivated. When the list of deactivated nodes changes, the GCC is recomputed and shown to the user by highlighting features included in the GCC.
https://github.com/OpenGeoscience/uvdat/assets/44912689/76c50232-fa29-40d2-8550-deb874682d90

Deactivate nodes

---

uvdat/core/views.py
web/src/App.vue
web/src/api/rest.ts
web/src/components/DrawerContents.vue
web/src/components/OptionsDrawerContents.vue
web/src/types.ts
web/src/utils.js

This PR makes the following UI changes:
- Organize available layers by category, using expansion panels to show/hide groups
- Move the options panel to the righthand side of the map to create more visual separation between the two panels
- Use a gear icon to open the options panel, shown in both the active layers list and the available layers list (if a layer is active)
- Add a toggle to the options panel for any raster dataset "Show raster tooltip". When enabled, mousing over the raster will give an approximate value. Values are approximate because the data is received at a 1/10 resolution to reduce load time, and because mouse position to array index conversion is done by proportion of coordinates.

UI updates

---

web/src/App.vue
web/src/components/MainDrawerContents.vue
web/src/components/OptionsDrawerContents.vue
web/src/store.ts
web/src/utils.js

This PR is intended to fix any unexpected behavior we found with the map layers. This includes the following:
Additionally, a new layer visibility feature was added:

Layer Visibility Logic

---

uvdat/core/tasks/conversion.py
web/src/utils.js

@AlmightyYakob noticed that when we use tiled geojsons, vector data is blurry at high zoom levels. For small datasets, we can load in the whole geojson without too much wait time, so the tiling is not as necessary.
This PR reduces the role of tiled geojsons to large datasets only. The tiling step is now not being performed on small datasets, so they will have no file saved to the `tiled_geo_file` field. The client-side code to render a layer on the map will now determine whether to tile the layer by whether `tiled_geo_file` is defined for that dataset.

Only use vector tiles on large datasets

---

dev/.env.docker-compose
dev/.env.docker-compose-native
sample_data/datasets.json
uvdat/core/tasks/conversion.py
web/src/utils.js

This PR adds 9 datasets to `datasets.json`. Running `python manage.py populate` in the Django container will make these datasets available on the map. 
- 9 inch sea level rise
- 9 inch 10 year flood
- 9 inch 100 year flood
- 21 inch sea level rise
- 21 inch 10 year flood
- 21 inch 100 year flood
- 36 inch sea level rise
- 36 inch 10 year flood
- 36 inch 100 year flood
The below screenshot shows the 9 inch 10 year Flood Dataset:

Add flood datasets

---

uvdat/core/serializers.py
uvdat/core/tasks/networks.py
uvdat/core/tasks/simulations.py
uvdat/core/views.py
web/src/components/NodeAnimation.vue
web/src/components/SimulationsPanel.vue

This PR adds a new Simulation type, "Recovery Scenario". For its input arguments, the user can select the following:
- an existing SimulationResult object from a node failure simulation
- a recovery mode from a list of strings: random, betweenness, degree, information, eigenvector, load, closeness, second order
The implementation of this simulation utilizes a function written by Jack Watson at NEU, shared with us for this simulation. The options available in that function determine the list of available recovery modes.
The animation of the results of this simulation only required a slight modification to the `NodeFailureAnimation` component, now renamed `NodeAnimation`. The component now accepts a list of `node_recoveries` alongside the list of `node_failures`. If `node_recoveries` is …

Recovery simulations

---

setup.py

Supercedes #22 
Fixes the following error showing up in Django locally
```
django.core.exceptions.ImproperlyConfigured: allauth.account.middleware.AccountMiddleware must be added to settings.MIDDLEWARE
```

Pin django-allauth to <0.56.0

---

web/src/components/MainDrawerContents.vue
web/src/components/OptionsDrawerContents.vue
web/src/components/map/ActiveLayers.vue
web/src/layers.ts

Fixes #31 
This PR also fixes the behavior in the raster slider / number input.
The underlying issue that was causing #31 to occur was the fact that we were deleting and re-adding a layer to the map, for two different use cases at the same time:
1. If we change any styling of a raster (because the style params are encoded in the layer source URL)
2. If we enable/disable the network vis mode of a network dataset (since they exist as two separate layers)
Since we heavily rely on consistent layer IDs, and removing/adding a layer to a map changes the layer ID, this was causing some weird behavior. This PR changes the behavior to directly handle raster styling changes, as well as node network visualization toggling.

Fix Active Layers behavior

---

.github/workflows/docker_image.yml
.github/workflows/release.yml
dev/Dockerfile
docker-compose.override.yml

This PR changes the Dockerfile used by the Django and Celery containers to make it more portable. The same Dockerfile is now used to publish an image on `ghcr.io`, which is publicly accessible here: https://github.com/orgs/OpenGeoscience/packages?repo_name=uvdat. We can use this server image on other projects where only the client application needs custom code.

Publishing server code as Docker image

---

.github/workflows/ci.yml

Previously, we used a GH action from `adambirds` to run our CI tests in the docker compose environment. It appears that it stopped working recently, because we consistently get errors like this for both our `pytest` and `check-migrations` jobs:
This PR switches to a similar GH action from `hoverkraft-tech`. There is a bit of syntax difference, but it achieves the same goal of running our tests in the docker compose environment.

Change docker compose GH Action

---

setup.py

This PR adds version specifications to dependencies listed in `setup.py` and removes dependencies previously used for static vector tile generation.

Pin dependency versions

---

sample_data/use_cases/new_york_energy/datasets.json
sample_data/use_cases/new_york_energy/import_networks.py

This PR updates the reference to the NY Grid data on [DKC](https://data.kitware.com/#collection/649079b9f04fb368544295e1/folder/66a289dc5d2551c516b1e4f8). The populate script now pulls v2 of this data. The following improvements were made to the NY Grid networks:
- Remove non-intersection nodes and merge edges across removed nodes (this results in the removal of approximately 40% of features)
- Add county_name, is_substation, connected_substation_name, and tree_depth to node and edge metadata
- Remove metadata with empty keys
The following steps describe how to use the new data:
- Switch to this branch
- Delete the cached file at `sample_data/downloads/nyc/networks.zip`
- Run `python manage.py populate new_york_energy --dataset_indexes 3 --include_large` in the Django container and wait …

Use improved NY Grid data

---

uvdat/core/models/networks.py
uvdat/core/rest/dataset.py

Since we're dealing with larger networks now (i.e. the boston roads dataset), the current algorithm for finding the GCC doesn't perform well enough. An example query on the boston roads dataset takes ~46 seconds. That same query takes ~40ms with this native Postgres query.
@annehaley PTAL and let me know if this maintains the same semantics as the original query.

Implement GCC algorithm in native Postgres

---

.github/workflows/ci.yml

This PR modifies the lint job in our CI tests to prevent the occurence of `error: externally-managed-environment` during the `pip install tox` step. The error message recommends using pipx for environment management, so this PR uses a `pipx` Github action to complete the installation of tox prior to running the lint command.
See [this workflow run](https://github.com/OpenGeoscience/uvdat/actions/runs/11276851895/job/31361638107) for an example of the error.

Use `pipx` for package installation in CI

---

setup.py
uvdat/core/rest/project.py
uvdat/core/rest/serializers.py
web/package-lock.json
web/package.json
web/src/App.vue
web/src/api/auth.js
web/src/api/rest.ts
web/src/components/AccessControl.vue
web/src/components/DatasetList.vue
web/src/components/MainDrawerContents.vue
web/src/components/ProjectConfig.vue
web/src/components/ProjectContents.vue
web/src/components/SimulationsPanel.vue
web/src/components/map/Map.vue
web/src/layers.ts
web/src/main.ts
web/src/store.ts
web/src/storeFunctions.ts
web/src/types.ts

Resolves #57. Resolves #58.
This PR adds a Project Configuration UI and improves the sidebar UI according to these [Figma Mockups](https://www.figma.com/design/OQ7RqVWPSlsyNMcLeI4j69/UVDAT?node-id=0-1&node-type=canvas) by @faiza-a.
Demo video on Drive:
https://drive.google.com/file/d/1M0vY9fUM-gY7AXQXNeyzN7kHj6TwVvRF/view?usp=sharing

Project Configuration UI

---

docker-compose.override.yml
pyproject.toml
setup.py
web/package-lock.json
web/package.json
web/src/App.vue
web/vue.config.js

This PR adds a menu to the toolbar title, which displays the following on hover:
- A link to this repository
- The current version string (full string if the repo is "dirty", tag-only otherwise) and a button to copy to clipboard
- The current version hash and a button to copy to clipboard
This PR also configures semantic release to update the version strings in `setup.py` and `web/package.json` upon release.
Resolves #65.

Version Tags

---

.pre-commit-config.yaml
setup.py

Resolves #88.
This PR adds `.pre-commit-config.yaml` to the top-level of this repository so that we can run pre-commit checks during development. These checks include linting with `flake8` and confirming that the commit message follows [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) structure (so that our semantic release CI job can interpret them).
To install:
```
pip install pre-commit
pre-commit install --hook-type commit-msg
```

Add precommit

---

uvdat/core/tasks/map_layers.py

- `style_options` can be None, since we don't have schema validation for input `datasets.json`
- Passing in a vector filename with an unsupported extension results in `geojson_data` not being defined.

Fix edge cases with create_{vector,raster}_map_layer

---

sample_data/ingest_use_case.py
sample_data/use_cases/la_wildfires/datasets.json
sample_data/use_cases/la_wildfires/ingest.py
sample_data/use_cases/la_wildfires/projects.json
uvdat/core/management/commands/populate.py

Datasets:
- MODIS 1km 48h USA + Hawaii: MODIS 1km USA (Conterminous) + Hawaii 48h shapefile. From: https://firms.modaps.eosdis.nasa.gov/active_fire/
- USA Palisades + Eaton Wildfire Perimeters: NIFC, taken on Feb 4, 2025. From: https://data-nifc.opendata.arcgis.com/
- USA Palisades + Eaton Wildfire Incidents: IRWIN, taken on Feb 4, 2025. From: https://forestsandrangelands.gov/WFIT/applications/IRWIN/index.shtml
- California Fire Perimeters: NIFC + FIRIS, taken Feb 4, 2025. From: https://www.fire.ca.gov/incidents/2025/1/7/palisades-fire
- Palisades Satellite Imager: MAXAR, Jan 14, 2025. From: https://registry.opendata.aws/maxar-open-data/
- Eaton/Altadena Satellite Imagery: MAXAR, Jan 14-19, 2025. From: https://registry.opendata.aws/maxar-open-data/
The satellite images cover smaller areas …

Add LA wildfires as a use-case

---

uvdat/core/admin.py
uvdat/core/rest/__init__.py
uvdat/core/rest/dataset.py
uvdat/core/rest/networks.py
uvdat/core/rest/serializers.py
uvdat/core/rest/tokenauth.py
uvdat/core/tasks/networks.py
uvdat/core/tests/test_dataset.py
uvdat/core/tests/test_network.py
uvdat/urls.py

In the course of continuing UI updates on #102, I found some more server-side changes that are needed to use the new Network model in our API. This includes an update to the new `TokenAuth` class and a new set of viewpoints for Networks. The client will now leverage these endpoints for Network-related logic (rather than going through Dataset endpoints, since the relationship between a Network and a Dataset is no longer one-to-one).

Additional API updates

---

docs/setup.md

`docker-compose` has been deprecated for some time now.

docs: remove deprecated docker-compose commands from setup docs

---

web/src/components/map/MapTooltip.vue

Constrains the map tooltips to be 50% of the viewport height with overflow scrolling.

Constrain map tooltip height with scroll

---

web/src/components/sidebars/DatasetsPanel.vue
web/src/themes.ts

The "Add to Selected Layers" button tooltip covered the layer name. Move the tooltip to the bottom as to not obscure the layer name.
This PR has no dependency on #122, but it is stacked on top so that I didn't have to stash my other changes.

Show tooltips below layer name

---

web/src/store/layer.ts
web/src/store/map.ts
web/src/store/style.ts
web/src/types.ts

Closes #140
The primary way this is achieved is by adding a `multiFrame` metadata field to a layer upon creation, and then checking for that field when handling a layer click. Specifically, this is used to further filter out "clickable" layers, since any layer that is clicked but has an opacity of zero should also be removed from the list of "clickable" layers.

Only use opacity for visibility on multi-frame layers

---

sample_data/ingest_use_case.py
sample_data/use_cases/boston_floods/charts.json
sample_data/use_cases/boston_floods/datasets.json
sample_data/use_cases/la_wildfires/datasets.json
sample_data/use_cases/la_wildfires/ingest.py
sample_data/use_cases/new_york_energy/datasets.json
sample_data/use_cases/test/datasets.json
setup.py
uvdat/core/management/commands/populate.py
uvdat/core/tasks/conversion.py

Using [pooch](https://github.com/fatiando/pooch) for downloading data files uses file hashes to ensure that downloaded files are correct and complete. Resolves #107.
Adding the `--no_cache` argument to the populate command allows the user to force deletion of existing Datasets, FileItems, and Charts and create new ones. Resolves #157.

Update populate script

---

web/src/store/layer.ts
web/src/store/map.ts
web/src/store/style.ts
web/src/types.ts

Our current method of parsing layer and source IDs is done ad hoc everywhere it's needed. This PR introduces well defined functions for parsing source and layer IDs into their constituent parts.

Standardize handling of source and layer IDs

---

web/src/store/layer.ts
web/src/store/map.ts

Follow up fix to #174 
1. Rasters were adding layers as `tile` and `mask` instead of `raster` and `fill` (the maplibre layer type)
1.`bounds` was being appended to raster source IDs, instead of replacing `raster`

Fix inconsistent source/layer ID generation
